### ISSUE TITLE
Gittio support

### ISSUE THREAD

**Issue by drmas** [HazemKhaled/TiPushNotification#2]
To be able to provide a Gittio package, you have to follow this naming convention for your release:
`moduleid-platform-version.zip`
While you release package right now is 
`TiPushNotification-0.1.0.zip`

So, you need to rename the package to 
`TiPushNotification-commonjs-0.1.0.zip`

and it will be automatically discovered by Gittio.

**Comment by HazemKhaled** [comment]
Done, thanks

**Comment by drmas** [comment]
You may need to increase the version number, for correct indexing in Gittio.

**Comment by HazemKhaled** [comment]
@drmas still not working, we need your help @FokkeZB (y)

**Comment by FokkeZB** [comment]
```
2015-10-29 05:15:48:5421 #3946 [NOTICE] package: TiPushNotification
2015-10-29 05:15:48:6601 #3946 [NOTICE] https://api.github.com/repos/HazemKhaled/TiPushNotification/releases/2017753
2015-10-29 05:15:48:6602 #3946 [NOTICE] 
2015-10-29 05:15:48:6603 #3946 [NOTICE] no match
```

The issue is that the zip should be in all lowercase. I thought Titaniumifier fixed that.

**Comment by HazemKhaled** [comment]
Finally working, but module id changed
http://gitt.io/component/ti-push-notification

@FokkeZB Please delete the old one http://gitt.io/component/TiPushNotification

Thanks

**Comment by FokkeZB** [comment]
done!

**Comment by HazemKhaled** [comment]
Thanks a lot
