### ISSUE TITLE
Error about androd GCM module

### ISSUE THREAD

**Issue by kerberosargos** [HazemKhaled/TiPushNotification#3]
I have trouble about Android GCM module. I created  [ticket ](https://github.com/morinel/gcmpush/issues/12#issuecomment-153882266) on owner's github profile. Do you have any idea? Thank you in advance.

**Comment by MahmoudElmoghazy** [comment]
@HazemKhaled could you help us on this problem ?

**Comment by HazemKhaled** [comment]
Check last updated release, it has to fix this issue

https://github.com/morinel/gcmpush/
