### ISSUE TITLE
Question about backend

### ISSUE THREAD

**Issue by DouglasHennrich** [HazemKhaled/TiPushNotification#5]
Hi!

Every time the user open the app, it register the token on our backend server ? If so... there's a way to only register on backend once ?

Thanks =)

**Comment by HazemKhaled** [comment]
I'm not facing this issue actually, did you manage to pass it?

**Comment by DouglasHennrich** [comment]
I saw the http fired to backend every time we open the app and the code reads `tiPush.registerDevice()`. I have add an property check on the module to prevent to fire the http to backend =)

If we already have an token property, we don't fire to http.

**Comment by HazemKhaled** [comment]
:+1:

**Comment by DouglasHennrich** [comment]
maybe you should add this on module itself

**Comment by DouglasHennrich** [comment]
#7

**Comment by pakoArtal** [comment]
Hi @DouglasHennrich and @HazemKhaled,
I was in doubt about storing the device token and token expiration. I have just read this Apple's doc through [http://stackoverflow.com/questions/6652242/does-the-apns-device-token-ever-change-once-created/35488911#35488911](http://stackoverflow.com/questions/6652242/does-the-apns-device-token-ever-change-once-created/35488911#35488911): [https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html) : 

> Device tokens can change, so your app needs to reregister every time it is launched and pass the received token back to your server.

So, it seems the right thing is call registerDevice every time the app is launched, or we could : 
-  everytime we launch the App , generate a new token and compare it to the stored token and if they were different, send it to our backend

**Comment by pakoArtal** [comment]
I think this change would do it...

``` javascript
function deviceTokenSuccess(e) {
    if (ANDROID) {
      Ti.API.debug('[TiPush] Device Token:', e.registrationId);
      token = e.registrationId;
    } else if (IOS) {
      Ti.API.debug('[TiPush] Device Token:', e.deviceToken);
      token = e.deviceToken;
    }
    //that.token = token;
    // if the previous token is empty OR the generated token is not equal to the previous token we send it to our backend
    if (that.token === '' || token !== that.token) {
        var uploadParams = {};
        that.token = token;
        Ti.App.Properties.setString('TiPushNotification_Token', that.token);


        for (var key in that) {
            if (['backendUrl', 'getToken', 'registerDevice', 'cancelRegister', 'getObject'].indexOf(key) === -1) {
                uploadParams[key] = that[key];
                Ti.API.info('key: ' + key + '  valor: ' + that[key]);
            }
        }

        var xhr = Ti.Network.createHTTPClient({
          onload: function() {
            Ti.API.debug("[TiPush] Token sent to our backend");
          },
          onerror: function() {
            Ti.API.error("[TiPush] Can't send tokend to our backend");
          }
        });
        xhr.open("POST", that.backendUrl);
        xhr.send(uploadParams);
    }
  }
```
